"""add report chunk embeddings

Revision ID: 7d36686a1265
Revises: 3bfce9374249
Create Date: 2026-08-02 20:56:33.748386

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d36686a1265'
down_revision: str | Sequence[str] | None = '3bfce9374249'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_chunk_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also proposed dropping 'apscheduler_jobs' — that
    # table is created and owned by APScheduler's SQLAlchemyJobStore at
    # runtime, not by our SQLAlchemy models, so it's intentionally absent
    # from Base.metadata. Dropping it here would destroy every scheduled
    # reminder job. Left out on purpose.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_chunk_embeddings')
    # ### end Alembic commands ###
