"""
agents/registry.py

Declarative Agent Registry (v5) — documents what each agent in this
system reads, writes, and its governance tags, for explainability.

Stated plainly: this is **not** a runtime-enforced permission sandbox.
Enforcing it for real would mean routing every agent's data access
through a generic permission-checked proxy, which would mean rewriting
every agent in `agents/` — disproportionate scope for this pass, and it
would risk destabilizing the RBAC that's already correctly enforced at
the API boundary (`backend/deps.py`'s `require_role`/`require_patient_access`,
which every router already goes through regardless of which agent it
calls). What this *does* give you: a single, honest, inspectable answer
to "what can this agent touch," which is exactly the kind of thing a
recruiter or a real system audit would ask for — and it's true, because
it's generated by reading the actual code, not aspirational.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AgentCapability:
    name: str
    module: str
    description: str
    reads: list[str]
    writes: list[str]
    risk: str
    autonomy: str


AGENT_REGISTRY: list[AgentCapability] = [
    AgentCapability(
        name="Planner Agent",
        module="agents/planner_agent.py",
        description="Decomposes one free-text request into an ordered task list.",
        reads=["session.has_report"],
        writes=[],
        risk="—",
        autonomy="—",
    ),
    AgentCapability(
        name="Orchestrator",
        module="agents/orchestrator.py",
        description="Executes each task in order, carries session state, persists reports.",
        reads=["reports", "reminders", "conversation_history"],
        writes=["reports", "conversation_history"],
        risk="—",
        autonomy="—",
    ),
    AgentCapability(
        name="Supervisor Agent",
        module="agents/supervisor_agent.py",
        description="Runs the Orchestrator, then decides escalation from combined triage/critic/interaction signals.",
        reads=["triage result", "critic result", "interaction warnings"],
        writes=["agent_approvals (Postgres only)"],
        risk="—",
        autonomy="—",
    ),
    AgentCapability(
        name="Summarizer Agent",
        module="agents/summarizer_agent.py",
        description="Patient summary, key findings, abnormal-value flagging with evidence trail.",
        reads=["report text", "extracted entities"],
        writes=["reports.summary_json (cached)"],
        risk="R1",
        autonomy="A0",
    ),
    AgentCapability(
        name="QA (RAG) Agent",
        module="agents/qa_agent.py",
        description="TF-IDF + optional semantic retrieval, LLM answer grounded in retrieved report text.",
        reads=["report text", "report_chunk_embeddings (if enabled)", "conversation_history"],
        writes=[],
        risk="R1",
        autonomy="A0",
    ),
    AgentCapability(
        name="Critic / Evidence Verifier",
        module="agents/critic_agent.py",
        description="Checks a QA answer's sentences against its retrieved chunks for support.",
        reads=["QA answer + retrieved chunks"],
        writes=[],
        risk="R1",
        autonomy="A0",
    ),
    AgentCapability(
        name="Clinical Triage Agent",
        module="agents/triage_agent.py",
        description="Rule-based LOW/MEDIUM/HIGH/CRITICAL risk classification.",
        reads=["extracted entities", "lab readings", "raw user text"],
        writes=[],
        risk="R2",
        autonomy="A0",
    ),
    AgentCapability(
        name="Reminder Agent",
        module="agents/reminder_agent.py",
        description="CRUD for medicine reminders, gated on extraction confidence.",
        reads=["reminders"],
        writes=["reminders"],
        risk="R0",
        autonomy="A2",
    ),
    AgentCapability(
        name="Drug Interaction Agent",
        module="agents/drug_interaction_agent.py",
        description="Curated interaction cross-check across known medicines.",
        reads=["data/medical_vocab/drug_interactions.json", "reminders", "extracted entities"],
        writes=[],
        risk="R2",
        autonomy="A0",
    ),
    AgentCapability(
        name="Clinical Timeline Agent",
        module="agents/timeline_agent.py",
        description="Chronological diff of entities across every report on file.",
        reads=["reports"],
        writes=["reports.entities_json (cached)"],
        risk="R1",
        autonomy="A0",
    ),
    AgentCapability(
        name="Report Generator Agent",
        module="agents/report_generator_agent.py",
        description="Builds the downloadable doctor-summary PDF.",
        reads=["summary", "entities", "reminders", "qa_history"],
        writes=["reports/ directory (PDF file)"],
        risk="R1",
        autonomy="A1",
    ),
    AgentCapability(
        name="Transcript Agent",
        module="agents/transcript_agent.py",
        description="Structures a consultation transcript into a draft SOAP note.",
        reads=["transcript text"],
        writes=["soap_notes (via backend/routers/transcripts.py)"],
        risk="R1",
        autonomy="A1",
    ),
    AgentCapability(
        name="Differential Reasoning Agent",
        module="agents/differential_agent.py",
        description="Independent evidence-grounded differential diagnosis generation.",
        reads=["extracted entities", "lab readings", "user text"],
        writes=[],
        risk="R2",
        autonomy="A1",
    ),
    AgentCapability(
        name="Lab Trend Analyst Agent",
        module="agents/lab_trend_agent.py",
        description="Mathematical rate-of-change (ΔValue/Δt) & trajectory alert detection.",
        reads=["lab readings across reports"],
        writes=[],
        risk="R2",
        autonomy="A0",
    ),
    AgentCapability(
        name="Multi-Agent Consensus Engine",
        module="agents/consensus_engine.py",
        description="Evidence-weighted multi-agent aggregation, dispute detection, and deterministic safety vetoes.",
        reads=["differential candidate proposals", "critic review", "patient allergies"],
        writes=["agent_approvals (when disputed or vetoed)"],
        risk="R2",
        autonomy="A2",
    ),
]
